# Generated by Django 5.1.5 on 2025-02-02 22:53

import django.core.serializers.json
import django.db.models.deletion
import wagtail.fields
import wagtail_flexible_forms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0003_formpage_formfield"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamFormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "form_fields",
                    wagtail.fields.StreamField(
                        [("sf_step", 27)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Name", "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Label"}),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Help text", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Required", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("email", "Email"), ("url", "URL")],
                                    "label": "Format",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Default value", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("format", 4),
                                        ("default_value", 5),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Default value", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("default_value", 7),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            9: ("wagtail.blocks.CharBlock", (), {"label": "Checkbox"}),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("checkboxes", 10),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            12: ("wagtail.blocks.CharBlock", (), {"label": "Choice"}),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("choices", 13),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            15: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"required": False},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("default_value", 15),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            17: ("wagtail.blocks.DateBlock", (), {"required": False}),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("default_value", 17),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            19: ("wagtail.blocks.TimeBlock", (), {"required": False}),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("default_value", 19),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            21: (
                                "wagtail.blocks.DateTimeBlock",
                                (),
                                {"required": False},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                        ("default_value", 21),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("field_label", 1),
                                        ("help_text", 2),
                                        ("required", 3),
                                    ]
                                ],
                                {"group": "Fields"},
                            ),
                            24: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"group": "Content"},
                            ),
                            25: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"group": "Content"},
                            ),
                            26: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("sf_singleline", 6),
                                        ("sf_multiline", 8),
                                        ("sf_checkboxes", 11),
                                        ("sf_radios", 14),
                                        ("sf_dropdown", 14),
                                        ("sf_checkbox", 16),
                                        ("sf_date", 18),
                                        ("sf_time", 20),
                                        ("sf_datetime", 22),
                                        ("sf_image", 23),
                                        ("sf_file", 23),
                                        ("text", 24),
                                        ("image", 25),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("form_fields", 26)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_flexible_forms.models.StreamFormMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="MySubmissionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submission_id", models.TextField()),
                ("data", models.TextField()),
                ("summary", models.TextField()),
                (
                    "submission_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MySessionFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="submit time"),
                ),
                (
                    "session_key",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Not submitted"),
                            ("complete", "Complete"),
                            ("reviewed", "Under consideration"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="incomplete",
                        max_length=10,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "form submission",
                "verbose_name_plural": "form submissions",
                "abstract": False,
                "unique_together": {("page", "session_key"), ("page", "user")},
            },
        ),
    ]
